[project]
name = "agent-adapter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agent-framework>=1.0.0b251120",
    "python-dotenv>=1.1.1",
]
